[project]
name = "conic"
version = "0.4.0"
description = "A SCPTu Data-Driven Evaluator."
readme = "README.md"
license = "AGPL-3.0-or-later"
authors = [
    { name = "Francesco Franco", email = "ffrancoa97@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "polars>=1.40.1",
    "pydantic>=2.13.4",
]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[dependency-groups]
dev = [
    "ipython>=9.13.0",
    "pytest>=9.0.3",
    "pytest-benchmark>=5.2.3",
    "ruff>=0.15.14",
]

[tool.maturin]
module-name = "conic._lib"
python-packages = ["conic"]
python-source = "src"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "src/**/*.rs" }, { file = "Cargo.toml" }, { file = "Cargo.lock" }]

[tool.ruff]
target-version = "py312"
line-length = 88
extend-exclude = ["src/conic/processing/"]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "W",   # pycodestyle warnings
    "I",   # isort
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "C4",  # flake8-comprehensions
    "RUF", # ruff-specific rules
]

ignore = [
    "C408",
    "E501",
    "RUF001",
    "UP045",
]

[tool.ruff.lint.isort]
lines-between-types = 1

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
