[package]
name = "conic-plugins"
version = "0.6.7"
edition = "2024"

[lib]
name = "_lib"
crate-type = ["cdylib"]

[dependencies]
conic-tools = { path = "tools" }
conic-calculate = { path = "calculate" }
conic-correlate = { path = "correlate" }
polars = { version = "0.54.4", default-features = false }
pyo3 = { version = "0.28.3", features = ["abi3-py312", "generate-import-lib"] }
pyo3-polars = { version = "0.27.0", features = ["derive", "dtype-struct", "dtype-array"] }
serde = { version = "1.0", features = ["derive"] }

[features]
default = ["extension-module"]
extension-module = ["pyo3/extension-module"]
