[package]
name        = "conic-cli"
version     = "0.1.0"
edition     = "2024"
license     = "MPL-2.0"
description = "Core library for `conic`"

[dependencies]
conic-core  = { path = "../conic-core" }