[package]
name = "conic-cli"
version = "0.6.8"
edition = "2024"
description = "A SCPTu Data-Driven Evaluator."

[[bin]]
name = "conic"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
conic-datasets = { path = "../conic-plugins/datasets" }
indicatif =  { version = "0.18.6" }
serde_json = { version = "1.0" }
